### ISSUE TITLE
Llama-2 models do not support `sliding_window` parameter

### ISSUE THREAD

**Issue by Bostoncake** [jzhang38/EasyContext#18]
In `train.py`, line 63 specified `sliding_window=None`. Actually, if Llama-2 models are used, the initialization function does not support this parameter. I guess this is modified from Mistral training scripts. 

Simply getting rid of this parameter works fine for me.

**Comment by jzhang38** [comment]
Strangely I recall it did not produce any error on my end with transformer 4.39.1 and llama.
I have that toggle because I also played with mistral.
I will re-check it maybe tonight.

**Comment by jzhang38** [comment]
Hi seems that it does not produce errors on my end.

**Comment by Bostoncake** [comment]
> Hi seems that it does not produce errors on my end.

It seems that this error occurs in my training environment where transformers=4.39.0. The training gives appropriate results, though.
