### ISSUE TITLE
Appending answer_ids to prompt in `eval_needle.py`

### ISSUE THREAD

**Issue by shan18** [jzhang38/EasyContext#19]
Hi,

In `eval_needle.py`, I see that the `answer_ids` are being appended to the input prompt.
https://github.com/jzhang38/EasyContext/blob/d6a7f2d74b08fc8049ec4a8146ef245051a669e3/eval_needle.py#L40

Could you please help me understand why this was implemented this way?

Wouldn't that make the model generate output in teacher-forcing mode instead of doing autoregressive decoding?

**Comment by jzhang38** [comment]
See https://github.com/jzhang38/EasyContext/issues/8

**Comment by shan18** [comment]
I see. Thanks a lot for the explanation.
