### ISSUE TITLE
shuffle bug?

### ISSUE THREAD

**Issue by fmmoret** [jzhang38/EasyContext#25]
Is this second shuffle a bug in zig-zag mode?

https://github.com/jzhang38/EasyContext/blob/6dfd77e8f2a68bf522be8889e60c98c8e816e329/train.py#L84
The dataset is already shuffled a few lines up with a seed.

@jzhang38

**Comment by jzhang38** [comment]
> Is this second shuffle a bug in zig-zag mode?

Yeah shuffling twice is probably not necessary, but why do you think this shuffling is a bug? I am assuming each process would still produce the same data on each rank.

> Where does this synchronization happen? I don't see the dataloader getting treatment from any libs for the zigzag ring attn mode.

Here: https://github.com/jzhang38/EasyContext/blob/6dfd77e8f2a68bf522be8889e60c98c8e816e329/train.py#L117
