### ISSUE TITLE
Bug: Evals might be broken in pinned HF transformers version `cache=False`

### ISSUE THREAD

**Issue by michaelfeil** [jzhang38/EasyContext#26]
Checked out your evals!

I think this should affect the generation quality.
https://github.com/huggingface/transformers/pull/30380

**Comment by jzhang38** [comment]
Hi, thanks for the info. If I understand this correctly, it only affects the generate() function? We did not use the generate function in our eval. See https://github.com/jzhang38/EasyContext/issues/19

**Comment by michaelfeil** [comment]
Ah, gotcha. This should be irrelevant then, you are correct!
