### ISSUE TITLE
can training codellama? 

### ISSUE THREAD

**Issue by 5taku** [jzhang38/EasyContext#29]
Thank you very much for your code. 

I performed train.py with the codellama 34b base. 

This training went well and I confirmed that a checkpoint output of 76G, which is the same as codellama 34b, was generated. 
Afterwards, when trying to load the generated model through LlamaForCausalLM, the following error occurred. 

```
ValueError: Trying to set a tensor of shape torch.size([0]) in "weight" (which has shape torch.Size([32000, 8192])), this look incorrect.
```

Is there anything I missed or need to fix?

**Comment by jzhang38** [comment]
You need to remove the model.safetensors like this:

https://github.com/jzhang38/EasyContext/blob/3c68bd5602e3f37582f9bbe73ab083273bd4a1c7/train_scripts/EasyContext-1M-Llama-2-7B.sh#L22

I don't why this would happen.

**Comment by 5taku** [comment]
> You need to remove the model.safetensors like this:
> 
> https://github.com/jzhang38/EasyContext/blob/3c68bd5602e3f37582f9bbe73ab083273bd4a1c7/train_scripts/EasyContext-1M-Llama-2-7B.sh#L22
> 
> I don't why this would happen.

solved!!
thank you!!!  :)
