### ISSUE TITLE
Does the input sharding match exact optimization of long sequence?

### ISSUE THREAD

**Issue by guanzhchen** [jzhang38/EasyContext#3]
Thanks for your exciting work!

I found the extract_local function seems to split the input sequence length L into L/world_size. Are parameters optimized (backward) for each chunk rather than the whole long sequence? So have you tried if there are any approximation errors or the optimization is length-agnostic?

**Comment by jzhang38** [comment]
> Are parameters optimized (backward) for each chunk rather than the whole long sequence? 

The whole sequence.

> have you tried if there are any approximation errors or the optimization is length-agnostic?

https://github.com/zhuzilin/ring-flash-attention/blob/55ff66fd35f329dfcc24ce7a448bfdd532865966/test/test_zigzag_ring_flash_attn_func.py#L121

**Comment by guanzhchen** [comment]
That makes sense! Thank you!
