### ISSUE TITLE
Rotary embedding size missmatch

### ISSUE THREAD

**Issue by Toan-Do** [jzhang38/EasyContext#31]
Hi authors,

Thank you for great repo! I am testing with Llama3-72b and got error

[rank0]:   File "/home/ubuntu/miniconda3/envs/llm2/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 447, in forward
[rank0]:     query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)
[rank0]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/miniconda3/envs/llm2/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 206, in apply_rotary_pos_emb
[rank0]:     q_embed = (q * cos) + (rotate_half(q) * sin)
[rank0]:                ~~^~~~~
[rank0]: RuntimeError: The size of tensor a (3999) must match the size of tensor b (4000) at non-singleton dimension 2

Do you have any idea about that error?

**Comment by bernerprzemek** [comment]
Hi this is related to your dataset, when you tokenize don't forget apply padding and truncation (especially set padding='max_length'), additionally you can check if input_ids.shape == position_ids.shape in training loop e.g.
`for step, batch in enumerate(train_loader):
        input_ids = batch["input_ids"][..., : args.seq_length + 1][..., :-1]
        target_ids = batch["input_ids"][..., : args.seq_length + 1][..., 1:]
        position_ids = (
            torch.arange(args.seq_length).unsqueeze(0).expand(input_ids.shape[0], -1)
        )
        print(input_ids.shape, position_ids.shape)`

**Comment by 5taku** [comment]
> Hi this is related to your dataset, when you tokenize don't forget apply padding and truncation (especially set padding='max_length'), additionally you can check if input_ids.shape == position_ids.shape in training loop e.g.
> 
> ```
> for step, batch in enumerate(train_loader):
>         input_ids = batch["input_ids"][..., : args.seq_length + 1][..., :-1]
>         target_ids = batch["input_ids"][..., : args.seq_length + 1][..., 1:]
>         position_ids = (
>             torch.arange(args.seq_length).unsqueeze(0).expand(input_ids.shape[0], -1)
>         )
> 
>         print(input_ids.shape, position_ids.shape) # these values must be equal
> ```
> 
> in your case value is 3999 and 4000, for simplicity I recommend just `max_length=args.seq_length + 1` when tokenize, have no idea why author add this plus one in input and target id :), anyway seem that is what you missed

hello 
Thanks as always for good code.
The above issue has occurred and we are trying to resolve it.

args.add_argument("--seq-length", type=int, default=49152)

It was set to 

The input_ids of train dataset is 49152.
len(train_dataset[0]['input_ids']) -> 49152

The input_ids of train_loader is also 49152.
len(train_loader.sampler.data_source[0]['input_ids']) -> 49152

input_ids = batch["input_ids"][..., : args.seq_length + 1][..., :-1] 
After executing the above code 

print(input_ids.shape, position_ids.shape) # these values must be equal

The result is 

torch.Size([1, 49151]) torch.Size([1, 49152])

no see. 
I read the above comment but I don't understand it.

Can I solve the above issue?

**Comment by bernerprzemek** [comment]
Simply your input is too short, your input should be len(train_dataset[0]['input_ids']) == 49153.
or change args.add_argument("--seq-length", type=int, default=49153) and than probably it will work.

**Comment by 5taku** [comment]
Thank you very much for your reply.

Currently my dataset is cut to length 49152 and I expected to train with 49152 (48k).

According to the above, is it correct that the length of the dataset should be 49152+1 for 48k learning?

https://huggingface.co/datasets/PY007/slimpajama_llama_tokenized_upsample_4096_chunk_256K
 --chunk_size=256001 \

I think it's the same as in.

Actually, I changed seq_length to 49151 and confirmed that it worked well.

Is there a theoretical explanation for the above or a paper I can check?
I'm curious about the mechanism.

As always, thank you for your answers. :)
