### ISSUE TITLE
dataset description

### ISSUE THREAD

**Issue by sunying2018** [jzhang38/EasyContext#7]
Great work! Would it be possible to add some descriptions to clarify how the training dataset is generated?  For example, the two datasets used in the script: PY007/slimpajama_llama_tokenized_upsample_4096_chunk_256K and PY007/slimpajama_llama_tokenized_upsample_4096_chunk_1M. Thanks!

**Comment by jzhang38** [comment]
Just add some info to the dataset card: https://huggingface.co/datasets/PY007/slimpajama_llama_tokenized_upsample_4096_chunk_256K

**Comment by Bostoncake** [comment]
Both dataset cards specifies that --dataset_size=100m. However, calculation shows that 256K dataset contains 1B tokens, and 1M dataset contains 5B tokens.

**Comment by jzhang38** [comment]
@jzhang38 Yes you are correct. I will update the dataset card. Sorry for the typo.
